[gcp_service_account]
type = "service_account"
project_id = "credenciasestoque"
private_key_id = "f4d917bf933b60ae89f1f774c88e33fc9a389fa6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDmE7Fm4zlOyn6C
fuhSQy1eaTgJJhR1Iz1UJJ4NTwKtPMYkmQUXFLDxHgIR8N8d6dXvDs/TZG+Cks8b
sJOxelGV3Ie75r4cm5WI9LxyxyXyz8Q9UdQPTpsKIfQ4mj5CcigpoDQ3ydwRY3fk
VqU+kFoJrrOFhTznIu0CXPUP8EjhwN1a0XsxDPwPEns1MJ4JdSalQLESY7zRNpgQ
pCW0bGu3VJtCNF1w9J9RHzNVekOutlVKi/Ue4F7GLbpuVFgSW7rm0FRXACcC0/9g
Wbj81Kk5y3+XKQ1YqgGfshXEQQUAar8k4ghG+PSsPhs9ZvL9f+1CGFLLWmWoi8l/
VhZTb1m7AgMBAAECggUAUIZ89Sc7BAYgYBj9w+jqJJyL9bvDtjnGub/1J3BLXgmi
yeVaoDjoMwPPMqtM0+HnM/vJplGFK7ypSyYykw/eJSbhxNSeHlIf9Ka/nCZydDje
lJ2irFbVMacvnG3zs3rT7rm4/PukD9vx9tOSk0KfmLrx7x3ycm1JaaXSSalOQOB/
Vh2itkhJ/3W8kTTWf6G8mA2e7l2qok04OyWrrviGFWgxLmu19whqeNkxb4hgxltX
OBMLejf8BVoRIxPmpm96CMcvUgp7AlcUXK+FdnzGujEOK5lJ0vbXt0R9y97JPVkc
QLyHsJpcrpZ2txizUSjnwL9ZOiX6hI0qI8114u79LQKBgQDzsCKZbTZ6lcYDmuDB
1bhjqXwWGhvB0wpoz1auIqfoRyBPrcxV7bkdrUV8zgDFiSZTHy+Xc2sCWfWdTMRJ
AeEiNrn9y6Sa3G7elTlgpDz1Q3AjKFU0IXo+7mnawb82UCVInv0ijoEfJcZg+w6r
r3uN9PXVkE2vElehUVQNHqhIpwKBgQDxs4L4x4bK3qtWxicJkikNUQXNFmAFTkZo
DFFnM1hjKYJJIPA1a3HR+OYxchwAJncnEVveYNli/h90Rz8im9M/KLAh3PB+LFIG
McSB0cG595kgUy1dQApv2btl0BfNHQdxBcEWv5JD4imzBU68rx5quP8tQ4prrlHy
zy9bkuL0zQKBgEMX767GfwVpT0eW0OMNcOMfuuZq8dF/xZHt5DO1nv04+BB4DZZr
CVi+aC9gmJ3VlHO2Vmgggwn2ssVIaZKgTdgZsUPLWdq5bl0iQNX24kG0+577yb+MW
hI3nHoX4aikOD/XasF9fVPW6dNAmz3c9rYr8MuNGA91781ybA8VI95RpAoGAWqxn
dAEWVkEWsiUAPBzy/aXpsTi1qQfmbd5BI6Alhn3p/Jk4xDGcr5LaeK5ARuYnSSa/
+jsHEpYXIr4ft1IR+929xdZm+k6SLvS4raMNNEDo1zGdESCXScK7BMT+SNqdEg+A
kpInwwOzdQ+GrE5d8NeaE1cFNMRexeJn98ixD/kCgYEA2XAb3QrhzHnPtdVjU4PY
O/ecAlhSSSk3avzlFDqg3/2hUsK52hBYDlNb8Wttca36xmu5WG/jTCqs/xP2GJpt
3NCRPc5iYu3qVu44Iv1nTAePITpTInin01+r7wFkdbz01fkAPgEZ9K1mQ8Va5cFx
aUR4xdHR6sqMIogn2aiFr1Q=
-----END PRIVATE KEY-----
"""

client_email = "estoquecharqueloja@credenciasestoque.iam.gserviceaccount.com"
client_id = "109714934383059723238"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/estoquecharqueloja%40credenciasestoque.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
